//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_categories
    {
        public document_categories()
        {
            this.documents = new HashSet<documents>();
        }
    
        public string id { get; set; }
        public string category_name { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
    
        public virtual ICollection<documents> documents { get; set; }
    }
}
