//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_rsvp
    {
        public string id { get; set; }
        public string member_id { get; set; }
        public string meeting_id { get; set; }
        public Nullable<bool> is_attending { get; set; }
        public Nullable<bool> is_bringing_friend { get; set; }
    
        public virtual meetings meetings { get; set; }
        public virtual members members { get; set; }
    }
}
