//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers_locations
    {
        public string id { get; set; }
        public string supplier_id { get; set; }
        public string physical_address { get; set; }
        public string telephone_number { get; set; }
        public Nullable<float> lng { get; set; }
        public Nullable<float> lat { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
    
        public virtual suppliers suppliers { get; set; }
    }
}
