//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.MySql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wwsaEntities : DbContext
    {
        public wwsaEntities()
            : base("name=wwsaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<youtube_recommendations> youtube_recommendations { get; set; }
        public DbSet<suppliers> suppliers { get; set; }
        public DbSet<suppliers_locations> suppliers_locations { get; set; }
        public DbSet<tools> tools { get; set; }
        public DbSet<members> members { get; set; }
        public DbSet<document_categories> document_categories { get; set; }
        public DbSet<documents> documents { get; set; }
        public DbSet<meeting_rsvp> meeting_rsvp { get; set; }
        public DbSet<meetings> meetings { get; set; }
    }
}
